const X_API_Key = "$$$";
const Customer_ID = "$$$";
export const headers = {
    'Content-Type': 'application/json',
    'x-api-key': X_API_Key,
    'customer-id': Customer_ID
};
export const chatCompletions = {
    path: "chat/completions",
    body: (messages) => ({
        model: "gpt-3.5-turbo",
        messages: messages 
    })
};

const data = {
    "ZipCode 22236": {
        "Traditional restaurant": 2,
        "Juice shop": 1,
        "Yemenite restaurant": 1,
        "Coffee shop": 5,
        "Cafe": 7,
        "Cafe teria": 2,
        "Butcher shop": 1,
        "Traditional teahouse": 1,
        "Historical landmark": 1,
        "Archaeological museum": 2,
        "Coffee store": 1,
        "Watch store": 1,
        "ALLRestaurants": 13,
        "TotalReviews": 8832,
        "AverageRate": 4.251515151515151,
        "24HoursBusinesses": 1,
        "LevelPrice": "Mid-range"
    },
    "ZipCode 22443": {
        "Fast food restaurant": 8,
        "Fish restaurant": 2,
        "Creole restaurant": 1,
        "Seafood restaurant": 1,
        "Hamburger restaurant": 1,
        "Pizza restaurant": 1,
        "Chicken restaurant": 4,
        "Buffet restaurant": 2,
        "Shawarma restaurant": 3,
        "Brunch restaurant": 1,
        "Coffee shop": 4,
        "Yemenite restaurant": 1,
        "Breakfast restaurant": 1,
        "Donut shop": 1,
        "Tea house": 1,
        "Juice shop": 1,
        "ALLRestaurants": 49,
        "TotalReviews": 7904,
        "AverageRate": 4.0680000000000005,
        "24HoursBusinesses": 3,
        "LevelPrice": "Budget"
    },
    "ZipCode 23218": {
        "Sri Lankan restaurant": 2,
        "Indian restaurant": 2,
        "Chicken restaurant": 2,
        "Health food restaurant": 1,
        "Indonesian restaurant": 1,
        "Turkish restaurant": 1,
        "Syrian restaurant": 1,
        "Yemenite restaurant": 1,
        "Shopping mall": 1,
        "Coffee shop": 6,
        "Cafe": 10,
        "Seafood restaurant": 1,
        "Supermarket": 6,
        "Medical equipment supplier": 1,
        "Butcher shop": 1,
        "Ice cream shop": 1,
        "Hotel": 2,
        "Restaurant supply store": 2,
        "Art gallery": 1,
        "Fish store": 1,
        "Bakery": 1,
        "Juice shop": 1,
        "Furniture accessories": 1,
        "Gym": 1,
        "Theme park": 1,
        "Banquet hall": 1,
        "Kitchen supply store": 1,
        "Security system supplier": 1,
        "Chocolate shop": 1,
        "Medical supply store": 1,
        "Sports club": 1,
        "Corporate office": 2,
        "Public university": 3,
        "Pharmacy": 1,
        "Gas cylinders supplier": 1,
        "Bottled water supplier": 1,
        "Cell phone store": 3,
        "Sports complex": 1,
        "Grocery store": 2,
        "Florist": 1,
        "Furniture store": 1,
        "International school": 1,
        "Computer store": 1,
        "ALLRestaurants": 18,
        "TotalReviews": 31102,
        "AverageRate": 4.075641025641027,
        "24HoursBusinesses": 5,
        "LevelPrice": "Budget"
    },
    "ZipCode 23342": {
        "Asian restaurant": 4,
        "Indian restaurant": 3,
        "Javanese restaurant": 1,
        "Seafood restaurant": 2,
        "Pakistani restaurant": 3,
        "Health food restaurant": 1,
        "Schools": 7,
        "Cafe": 1,
        "Coffee shop": 1,
        "ALLRestaurants": 18,
        "TotalReviews": 15052,
        "AverageRate": 4.0346153846153845,
        "24HoursBusinesses": 1,
        "LevelPrice": "Premium"
    },
    "ZipCode 23425": {
        "Fast food restaurant": 5,
        "Vegan restaurant": 1,
        "Pancake restaurant": 1,
        "Pizza restaurant": 1,
        "Seafood restaurant": 1,
        "Barbecue restaurant": 1,
        "Indian restaurant": 1,
        "Breakfast restaurant": 1,
        "Bakery": 1,
        "Diner": 1,
        "Pizza takeaway": 2,
        "Tapas restaurant": 1,
        "Coffee shop": 6,
        "Cafe": 7,
        "Hotel": 4,
        "Small plates restaurant": 1,
        "Donut shop": 4,
        "Juice shop": 1,
        "Ice cream shop": 1,
        "Candy store": 1,
        "Amusement center": 1,
        "Country food restaurant": 1,
        "Outlet mall": 2,
        "American restaurant": 2,
        "Shopping mall": 2,
        "Mosque": 1,
        "Furnished apartment building": 1,
        "Furniture store": 1,
        "Home goods store": 2,
        "Nut store": 1,
        "Supermarket": 1,
        "Grocery store": 2,
        "Hardware store": 1,
        "Soccer field": 1,
        "ALLRestaurants": 46,
        "TotalReviews": 83031,
        "AverageRate": 4.082022471910115,
        "24HoursBusinesses": 9,
        "LevelPrice": "Budget"
    },
    "ZipCode 23451": {
        "Fast food restaurant": 18,
        "Chicken restaurant": 4,
        "Asian restaurant": 2,
        "Seafood restaurant": 3,
        "Family restaurant": 1,
        "Shawarma restaurant": 1,
        "Dessert restaurant": 1,
        "Coffee shop": 8,
        "Pizza restaurant": 1,
        "Indian restaurant": 1,
        "Cafe": 4,
        "Juice shop": 4,
        "Breakfast restaurant": 2,
        "Koshari restaurant": 1,
        "Sandwich shop": 1,
        "Candy store": 1,
        "ALLRestaurants": 78,
        "TotalReviews": 24285,
        "AverageRate": 4.1765432098765425,
        "24HoursBusinesses": 9,
        "LevelPrice": "Mid-range"
    },
    "ZipCode 23623": {
        "Seafood restaurant": 1,
        "Chinese restaurant": 1,
        "African restaurant": 1,
        "Japanese restaurant": 1,
        "Pizza restaurant": 1,
        "Hamburger restaurant": 2,
        "Fast food restaurant": 1,
        "Breakfast restaurant": 2,
        "Indonesian restaurant": 1,
        "Barbecue restaurant": 1,
        "Italian restaurant": 2,
        "Vegan restaurant": 1,
        "Bakery": 3,
        "Cafe": 7,
        "Hotel": 1,
        "Coffee shop": 5,
        "Cafe teria": 1,
        "Donut shop": 2,
        "Ice cream shop": 1,
        "American restaurant": 1,
        "ALLRestaurants": 24,
        "TotalReviews": 32330,
        "AverageRate": 4.016666666666666,
        "24HoursBusinesses": 6,
        "LevelPrice": "Premium"
    },
    "ZipCode 23715": {
        "Malaysian restaurant": 1,
        "Chicken restaurant": 1,
        "Sandwich shop": 1,
        "Cafe": 1,
        "Indian restaurant": 1,
        "Seafood restaurant": 1,
        "Pizza restaurant": 1,
        "Falafel restaurant": 1,
        "Coffee shop": 3,
        "Ice cream shop": 2,
        "Shopping mall": 1,
        "Art Cafe": 1,
        "Hospital": 1,
        "Preparatory school": 1,
        "ALLRestaurants": 12,
        "TotalReviews": 9529,
        "AverageRate": 4.172727272727273,
        "24HoursBusinesses": 1,
        "LevelPrice": "Premium"
    },
    "ZipCode 23734": {
        "Pizza restaurant": 1,
        "Seafood restaurant": 3,
        "Barbecue restaurant": 1,
        "Fast food restaurant": 2,
        "Indian restaurant": 1,
        "Cafe": 4,
        "ALLRestaurants": 14,
        "TotalReviews": 9728,
        "AverageRate": 4.072222222222223,
        "24HoursBusinesses": 0,
        "LevelPrice": "Mid-range"
    },
    "ZipCode 23786": {
        "Hamburger restaurant": 1,
        "Fast food restaurant": 3,
        "Murtabak restaurant": 1,
        "Fish & chips restaurant": 1,
        "Breakfast restaurant": 1,
        "ALLRestaurants": 17,
        "TotalReviews": 3054,
        "AverageRate": 3.8187499999999996,
        "24HoursBusinesses": 2,
        "LevelPrice": "Budget"
    },
    "ZipCode 21146": {
        "Italian restaurant": 1,
        "Shawarma restaurant": 1,
        "Asian restaurant": 1,
        "Shopping mall": 4,
        "Movie theater": 2,
        "Boutique": 1,
        "Clothing store": 4,
        "Lingerie store": 1,
        "Handbags shop": 1,
        "Women's clothing store": 1,
        "Cafe": 1,
        "ALLRestaurants": 4,
        "TotalReviews": 186753,
        "AverageRate": 3.80625,
        "24HoursBusinesses": 1,
        "LevelPrice": "Luxury"
    },
    "ZipCode 23435": {
        "Coffee shop": 39,
        "Cafe": 19,
        "Coffee roasters": 2,
        "Lounge": 4,
        "Sandwich shop": 2,
        "Donut shop": 2,
        "Creperie": 2,
        "Park": 1,
        "Karaoke bar": 1,
        "Art gallery": 2,
        "Spa and health club": 1,
        "Mediterranean restaurant": 3,
        "Japanese restaurant": 8,
        "Breakfast restaurant": 4,
        "Middle Eastern restaurant": 3,
        "Furnished apartment building": 2,
        "Seafood restaurant": 4,
        "Hamburger restaurant": 4,
        "Women's clothing store": 2,
        "Book store": 1,
        "Chicken restaurant": 2,
        "Butcher shop": 1,
        "Shopping mall": 1,
        "Juice shop": 2,
        "Consultant": 1,
        "Law firm": 1,
        "Modern British restaurant": 1,
        "Health food restaurant": 2,
        "Indian restaurant": 1,
        "Brunch restaurant": 1,
        "Pizza restaurant": 1,
        "Dessert shop": 1,
        "Falafel restaurant": 2,
        "School": 8,
        "Kindergarten": 1,
        "Preschool": 1,
        "ALLRestaurants": 69,
        "TotalReviews": 93419,
        "AverageRate": 4.206250000000002,
        "24HoursBusinesses": 18,
        "LevelPrice": "Premium"
    },
    "ZipCode 22338": {
        "Business park": 4,
        "Shopping mall": 3,
        "Fast food restaurant": 1,
        "Chicken restaurant": 1,
        "Cafe": 4,
        "Coffee shop": 6,
        "Ice cream shop": 3,
        "Supermarket": 1,
        "Movie theater": 3,
        "Hypermarket": 1,
        "Sunglasses store": 1,
        "School": 2,
        "Bakery": 1,
        "Discount store": 1,
        "Book store": 1,
        "ALLRestaurants": 7,
        "TotalReviews": 76485,
        "AverageRate": 4.213157894736843,
        "24HoursBusinesses": 2,
        "LevelPrice": "Budget"
    },
    "ZipCode 23233": {
        "Pizza restaurant": 1,
        "Cafe": 1,
        "Coffee shop": 1,
        "American restaurant": 1,
        "hotel": 2,
        "Bakery": 1,
        "School": 3,
        "Shopping mall": 2,
        "Gift wrap store": 1,
        "Hamburger restaurant": 1,
        "ALLRestaurants": 4,
        "TotalReviews": 15337,
        "AverageRate": 3.9899999999999998,
        "24HoursBusinesses": 0,
        "LevelPrice": "Mid-range"
    },
    "ZipCode 23541": {
        "Hotel": 1,
        "Hypermarket": 3,
        "Supermarket": 4,
        "Coffee shop": 9,
        "Cafe": 8,
        "Ice cream shop": 1,
        "Breakfast restaurant": 1,
        "Grocery store": 1,
        "Dessert shop": 1,
        "Fast food restaurant": 4,
        "Spice store": 1,
        "Shopping mall": 2,
        "Restaurant": 2,
        "Coffee": 4,
        "Ice cream": 1,
        "Flower market": 2,
        "ALLRestaurants": 12,
        "TotalReviews": 53140,
        "AverageRate": 4.0734693877551,
        "24HoursBusinesses": 8,
        "LevelPrice": "Premium"
    },
    "ZipCode 23526": {
        "Supermarket": 5,
        "Clothing store": 4,
        "Cosmetics store": 2,
        "Hypermarket": 3,
        "Women's clothing store": 1,
        "Baby store": 1,
        "Beauty supply store": 1,
        "Perfume store": 3,
        "Hookah store": 2,
        "Gift wrap store": 1,
        "Sports complex": 5,
        "Serviced apartment": 5,
        "Hotel": 5,
        "Corporate office": 2,
        "Outlet mall": 1,
        "Men's clothing store": 1,
        "Fast food restaurant": 4,
        "Group accommodation": 2,
        "Pizza restaurant": 1,
        "Jewelry store": 4,
        "Gym": 1,
        "Gas station": 1,
        "Amusement center": 1,
        "Watch store": 1,
        "School": 8,
        "Grocery store": 3,
        "Mosque": 1,
        "International airport": 3,
        "Holding company": 1,
        "International school": 1,
        "Private educational institution": 1,
        "Kindergarten": 3,
        "Religious school": 1,
        "Government school": 1,
        "Health food restaurant": 3,
        "Diner": 2,
        "Seafood restaurant": 3,
        "Donut shop": 3,
        "Ice cream shop": 7,
        "Coffee shop": 15,
        "Discount supermarket": 2,
        "Video game store": 2,
        "Dessert shop": 2,
        "Chocolate shop": 3,
        "Bakery": 2,
        "Juice shop": 1,
        "Dialysis center": 4,
        "Car repair and maintenance service": 2,
        "Cafe": 3,
        "Coffee store": 1,
        "Pool hall": 1,
        "Breakfast restaurant": 1,
        "Sandwich shop": 1,
        "Electronics store": 1,
        "Candy store": 2,
        "Holiday apartment rental": 2,
        "Confectionery": 1,
        "ALLRestaurants": 17,
        "TotalReviews": 129697,
        "AverageRate": 4.03294117647059,
        "24HoursBusinesses": 18,
        "LevelPrice": "Mid-range"
    }
};

export const systemContentTemplate = `

    please this is the new chat, new content and new chat, not related with previous content

    You are a helpful assistant that 
    suggests two places from this data:
    ${JSON.stringify(data)}

    that will be the just two best places for opening a new restaurant business. 

    depend on user input restaurant business, analysis this information to determine two best places for business

     just Example of Business Analytics Criteria Definition:
        - Number of similar activities nearby
        - Number of nearby activities
        - Average ratings for competitors
        - The crowding rate in each restaurant
        - Shopping and entertainment centers
        - Colleges, universities and schools
        - Compare products



   please the response in the following format, no text, no padding, no new lines, no special characters no any addition text
    [
        {
            zipCode: "",
            success: {
                percentage: "" //choices(Low, Medium, High),
                reasons: [//please write list of reasons for why this place is the best with details, at minimum 2 reasons, don't repeat the reasons in the second place
                    "",
                    ...
                ],
            },
            risk: {
                percentage: "" //choices(Low, Medium, High),
                risks: [//please write list of risk reasons for why this place is the best with details, at minimum 2 risks, don't repeat the risks in the second place
                    "",
                    ...
                ],
            },
        },
        ...
    ]

    please the return must return in Json Format that make to make easy to conver to object
`;
